default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
light-orange: styles/orange.scss
light-blue: styles/blue.scss
mastodon-original: styles/mastodon-orig.scss
contrast-original: styles/contrast-orig.scss
mastodon-light-original: styles/mastodon-light-orig.scss
