default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
mastodon-original: styles/mastodon-orig.scss
mastodon-light-original: styles/mastodon-light-orig.scss
orange: styles/orange.scss
